# Generated by Django 4.0.6 on 2022-09-28 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('mrn', models.CharField(max_length=100)),
                ('acc', models.CharField(max_length=100)),
                ('case_type', models.CharField(choices=[('MRA', 'GRASP MRA'), ('Onco', 'GRASP Onco')], default='MRA', max_length=4)),
                ('exam_time', models.DateTimeField()),
                ('receive_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('twix_id', models.CharField(max_length=10000)),
                ('case_location', models.CharField(max_length=10000)),
                ('incoming_payload', models.JSONField()),
                ('reader', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gravis_case',
            },
        ),
        migrations.CreateModel(
            name='DICOMSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_location', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.case')),
            ],
            options={
                'db_table': 'gravis_dicom_set',
            },
        ),
        migrations.CreateModel(
            name='DockerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=10000)),
                ('input_folder', models.CharField(max_length=10000)),
                ('output_folder', models.CharField(max_length=10000)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gravis_docker_job',
            },
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(default=uuid.uuid1, max_length=10000)),
                ('rq_id', models.CharField(max_length=10000)),
                ('results', models.CharField(max_length=100000)),
                ('complete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'gravis_image_job',
            },
        ),
        migrations.CreateModel(
            name='ProcessingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('json_result', models.JSONField(null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.case')),
                ('dicom_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.dicomset')),
            ],
            options={
                'db_table': 'gravis_processing_result',
            },
        ),
        migrations.AddField(
            model_name='dicomset',
            name='processing_result',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.processingresult'),
        ),
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_location', models.CharField(max_length=10000)),
                ('study_uid', models.CharField(max_length=100)),
                ('series_uid', models.CharField(max_length=100)),
                ('instance_uid', models.CharField(max_length=100)),
                ('json_metadata', models.JSONField()),
                ('dicom_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dicomset')),
            ],
            options={
                'db_table': 'gravis_dicom_instance',
            },
        ),
        migrations.AddConstraint(
            model_name='processingresult',
            constraint=models.CheckConstraint(check=models.Q(('json_result__isnull', False), ('dicom_set__isnull', False), _connector='OR'), name='both_dicom_set_and_json_result_cannot_be_null'),
        ),
        migrations.AddConstraint(
            model_name='dicominstance',
            constraint=models.UniqueConstraint(fields=('dicom_set', 'study_uid', 'series_uid', 'instance_uid'), name='unique_uids'),
        ),
    ]
