# Generated by Django 4.0.6 on 2022-08-02 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(default=uuid.uuid1, max_length=10000)),
                ('rq_id', models.CharField(max_length=10000)),
                ('results', models.CharField(max_length=100000)),
            ],
        ),
    ]
