# Generated by Django 4.0.6 on 2022-09-27 02:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_location', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'portal_case',
            },
        ),
        migrations.CreateModel(
            name='DockerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=10000)),
                ('input_folder', models.CharField(max_length=10000)),
                ('output_folder', models.CharField(max_length=10000)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ImageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_path', models.CharField(default=uuid.uuid1, max_length=10000)),
                ('rq_id', models.CharField(max_length=10000)),
                ('results', models.CharField(max_length=100000)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DICOMSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_location', models.CharField(max_length=10000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('json_payload', models.JSONField()),
                ('is_incoming', models.BooleanField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.case')),
            ],
            options={
                'db_table': 'portal_dicom_set',
            },
        ),
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_location', models.CharField(max_length=10000)),
                ('study_uid', models.CharField(max_length=100)),
                ('series_uid', models.CharField(max_length=100)),
                ('instance_uid', models.CharField(max_length=100)),
                ('json_metadata', models.JSONField()),
                ('dicom_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.dicomset')),
            ],
            options={
                'db_table': 'portal_dicom_instance',
            },
        ),
        migrations.AddConstraint(
            model_name='dicominstance',
            constraint=models.UniqueConstraint(fields=('dicom_set', 'study_uid', 'series_uid', 'instance_uid'), name='unique_uids'),
        ),
    ]
