# Generated by Django 4.0.6 on 2022-11-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('RCVD', 'Received'), ('QUED', 'Queued'), ('PROC', 'Processing'), ('RDY', 'Ready'), ('VIEW', 'Viewing'), ('COMP', 'Complete'), ('ARCH', 'Archived'), ('ERR', 'Error'), ('DEL', 'Delete')], default='RCVD', max_length=100),
        ),
    ]
