# Generated by Django 4.0.6 on 2022-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='error_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
