# Generated by Django 4.0.6 on 2022-10-11 04:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('RCVD', 'Received'), ('QUED', 'Queued'), ('PROC', 'Processing'), ('RDY', 'Ready'), ('VIEW', 'Viewing'), ('COMP', 'Complete'), ('ARCH', 'Archived'), ('ERR', 'Error')], default='RCVD', max_length=4),
        ),
        migrations.AlterField(
            model_name='dicominstance',
            name='dicom_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='portal.dicomset'),
        ),
        migrations.AlterField(
            model_name='dicomset',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_sets', to='portal.case'),
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('json_result', models.JSONField(null=True)),
                ('docker_image', models.CharField(max_length=100)),
                ('input_folder', models.CharField(max_length=1000)),
                ('output_folder', models.CharField(max_length=1000)),
                ('rq_id', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.case')),
                ('dicom_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.dicomset')),
            ],
        ),
        migrations.AlterField(
            model_name='dicomset',
            name='processing_result',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.processingjob'),
        ),
        migrations.DeleteModel(
            name='ProcessingResult',
        ),
    ]
