# Generated by Django 4.0.6 on 2022-10-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_case_status_alter_dicominstance_dicom_set_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processingjob',
            table='gravis_processing_job',
        ),
    ]
