# Generated by Django 4.0.6 on 2022-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('MRA', 'GRASP MRA'), ('Onco', 'GRASP Onco'), ('SVW', 'Series Viewer')], max_length=100, null=True),
        ),
    ]
