# Generated by Django 4.0.6 on 2022-11-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_processingjob_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicominstance',
            name='num_frames',
            field=models.IntegerField(null=True),
        ),
    ]
