# Generated by Django 4.0.6 on 2023-01-26 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0003_alter_case_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('file_location', models.CharField(max_length=1000, null=True)),
                ('data', models.JSONField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dicom_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='portal.dicomset')),
            ],
            options={
                'db_table': 'gravis_finding',
            },
        ),
    ]
