# Generated by Django 4.0.6 on 2022-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_processing_result_dicomset_processing_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomset',
            name='output_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
