# Generated by Django 4.0.6 on 2022-09-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_dockerjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_uid', models.CharField(max_length=100)),
                ('series_uid', models.CharField(max_length=100)),
                ('instance_uid', models.CharField(max_length=100)),
                ('file_location', models.CharField(max_length=10000)),
                ('json_metadata', models.JSONField(null=True)),
            ],
        ),
    ]
