# Generated by Django 4.0.6 on 2022-09-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_dicominstance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dicominstance',
            constraint=models.UniqueConstraint(fields=('study_uid', 'series_uid', 'instance_uid'), name='unique_uids'),
        ),
    ]
