# Generated by Django 4.0.6 on 2022-09-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_dicominstance_unique_uids'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicominstance',
            name='patient_name',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dicominstance',
            name='series_description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='dicominstance',
            name='study_description',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
