# Generated by Django 4.0.6 on 2023-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
