# Generated by Django 4.0.6 on 2022-09-20 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_dicominstance_patient_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_location', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='dicominstance',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='portal.case'),
        ),
    ]
