# Generated by Django 4.0.6 on 2023-02-13 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'), 
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='portal.case'),
        ),
        migrations.AddField(
            model_name='finding',
            name='dicom_location',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='gravis_user_profile',
        ),
    ]
