# Generated by Django 4.0.6 on 2022-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_case_dicominstance_case'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicominstance',
            name='unique_uids',
        ),
        migrations.AddConstraint(
            model_name='dicominstance',
            constraint=models.UniqueConstraint(fields=('study_uid', 'series_uid', 'instance_uid', 'case'), name='unique_uids'),
        ),
    ]
