# Generated by Django 4.0.6 on 2023-03-07 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0009_add_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(default=portal.models.ShadowCase.default_pt, max_length=50)),
                ('mrn', models.CharField(default=portal.models.ShadowCase.default_num, max_length=20)),
                ('acc', models.CharField(default=portal.models.ShadowCase.default_num, max_length=20)),
            ],
            options={
                'db_table': 'gravis_shadow_case',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portal.tag'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='shadow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case', to='portal.shadowcase'),
        ),
    ]
