# Generated by Django 4.0.6 on 2023-06-07 16:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_case_shadow_alter_shadowcase_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicominstance',
            name='image_position_patient',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=3),
        ),
        migrations.AddField(
            model_name='dicominstance',
            name='slice_z_position',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='dicomset',
            name='is_volume',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='dicomset',
            name='frame_of_reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dicomset',
            name='image_orientation_calc',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3), null=True, size=3),
        ),
        migrations.AddField(
            model_name='dicomset',
            name='image_orientation_calc_inv',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3), null=True, size=3),
        ),
        migrations.AddField(
            model_name='dicomset',
            name='image_orientation_patient',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=3), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_jobs', to='portal.case'),
        ),
        migrations.AddIndex(
            model_name='dicominstance',
            index=models.Index(fields=['dicom_set', 'series_uid', 'slice_z_position'], name='gravis_dico_dicom_s_1260e0_idx'),
        ),
    ]
