# Generated by Django 4.0.6 on 2023-10-02 16:32

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0012_dicominstance_image_position_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingjob',
            name='error_case_ok',
            field=models.BooleanField(null=True),
        ),
    ]
