site_name: GRAVIS Documentation
site_url: https://gravis-imaging.org/gravis
copyright: Copyright &copy; 2022 - 2024 Center for Advanced Imaging Innovation and Research (CAI<sup>2</sup>R)
theme:
  name: material
  palette:
    scheme: slate  
    primary: custom    
  favicon: images/favicon.png
  logo: images/favicon.png
  features:
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - site-urls
  - search  
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/gravis-imaging/gravis
repo_name: gravis-imaging/gravis
